# Generated by Django 5.2 on 2025-04-18 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(max_length=100)),
                ('id_examen', models.CharField(max_length=100, unique=True)),
                ('ubicacion_examen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FragmentoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fragmento', models.PositiveIntegerField()),
                ('total_fragmentos', models.PositiveIntegerField()),
                ('ubicacion_fragmento', models.URLField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='map_logic.examen')),
            ],
            options={
                'unique_together': {('examen', 'numero_fragmento')},
            },
        ),
    ]
