# Generated by Django 5.2 on 2025-04-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='id_examen',
            field=models.CharField(max_length=100),
        ),
    ]
